package com.stoonproduction.jobapplication.models;

import java.time.LocalDateTime;

public class JobSeeker extends User {
    private Long userId;
    private String name;
    private String resumeUrl;
    private String skills;

    // Constructor without 'userId' (for new JobSeeker - ID will be auto-generated by DB)
    public JobSeeker(String email, String password, UserRole role, String name, String resumeUrl, String skills) {
        super(email, password, role);
        this.name = name;
        this.resumeUrl = resumeUrl;
        this.skills = skills;
    }

    // Constructor with 'id' (for loading JobSeeker from database)
    public JobSeeker(Long id, String email, String password, UserRole role, LocalDateTime createdAt, Long userId, String name, String resumeUrl, String skills) {
        super(id, email, password, role, createdAt);
        this.userId = userId;
        this.name = name;
        this.resumeUrl = resumeUrl;
        this.skills = skills;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getResumeUrl() {
        return resumeUrl;
    }

    public void setResumeUrl(String resumeUrl) {
        this.resumeUrl = resumeUrl;
    }

    public String getSkills() {
        return skills;
    }

    public void setSkills(String skills) {
        this.skills = skills;
    }

    @Override
    public String toString() {
        return "JobSeeker{" +
                "userId=" + userId +
                ", name='" + name + '\'' +
                ", resumeUrl='" + resumeUrl + '\'' +
                ", skills='" + skills + '\'' +
                '}';
    }
}
